[[main]]
name = "about"
pageRef = "about"
weight = 10

[[main]]
name = "projects"
pageRef = "projects"
weight = 20

[[main]]
name = "skills"
pageRef = "skills"
weight = 30

[[main]]
name = "socials"
pageRef = "socials"
weight = 40

[[main]]
name = "connect"
pageRef = "connect"
weight = 50

[[main]]
identifier = "appearance"
weight = 99
[main.params]
action = "appearance"
