[[main]]
name = "about"
url = "/about/"
weight = 10

[[main]]
name = "projects"
url = "/projects/"
weight = 20

[[main]]
name = "open source"
url = "/open-source/"
weight = 25

[[main]]
name = "skills"
url = "/skills/"
weight = 30

[[main]]
name = "experience"
url = "/experience/"
weight = 35

[[main]]
name = "connect"
url = "/connect/"
weight = 40

[[main]]
identifier = "appearance"
weight = 99
[main.params]
action = "appearance"
