[[main]]
name = "about"
url = "/about/"
weight = 10

[[main]]
name = "projects"
url = "/projects/"
weight = 20

[[main]]
name = "open source"
url = "/open-source/"
weight = 25


[[main]]
name = "connect"
url = "/connect/"
weight = 40

[[main]]
name = "GitHub"
url = "https://github.com/shaivarth"
weight = 50
[main.params]
icon = "github"
showName = false
target = "_blank"

[[main]]
identifier = "appearance"
weight = 99
[main.params]
action = "appearance"
